apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: jobsync
webhooks:
  - name: jobsync.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 10
    clientConfig:
      service:
        name: jobsync
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVYUtLNFVjbktVTmY1bkQvdnJPTnVyUDNManpBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdNakU0Ck1ETXlPREF3V2hjTk1qY3dNakUzTURNeU9EQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMUXBBV20zCmxtLzBDdStjNUp0Y2JXZFUwZWJtYjJ1eFk4K1BHWHVqcmRsd1ZhTzltQVVWdDhhbnpyTm1NTGxBcm9RZHY2N3AKYVpuT3JzdGFwSGE1MHByZFpyeFQ0UXVzNVNUQzF6bUpVbkdOME9qaDN0TmluVFlNOEN3SmVOVC9Lb2FSZE1naQpGZGdZK1Y4dUlFWnArUXc5WnBMazRzYnJlK1I1V0daWmdsaEVFMEpVT1RTNWtIcFV0L2V2cUR3UFlWS1BYcE9LClFyQnJRWTltM01zM2NKSnhmbVA5Yy8wSldOaGJOL0tRcWFRZEZHZG0rRDdJSzlEMy93V2NRVjlJNHpUY1NRYWgKL09RQlZ1RGpwQlJXTkp0dGtmOFZPOGh5anZ4TGM2MWFRbXc4WjFwd3VXWG1oS3JMS1BwZmw0dUVhVDJnd05lUAp5djFTc1c3NmhTU0RFRkVDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkw1cFd3aldRTm5KRlpCNXoybGdUY1IxTTNrRk1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUNPQXM3QUZXTWNzY2VYbGp2SFdUSC9zaUJQRzRpSDZjdThLYkZGcVpPSXRnWWh1QnV6cnZXbgpheHB6UWFYZ3A4bEFUVmtUMG9oWUlHcjhEUExYMDhrZlYzQzhxSitFRUdTUTFCSXAwcVBlTEtIMkJ5OXhQTHd6Ckk4bTZ6U2tsdzRTODdnSTBxbEhsQUdlb1lLdjhialRUWkJwVU03VlRsL1VmelpXelE3ajgwWHZweE1udXJST04Ka1VLVmo0bjVRQlU4N1pTVC9zSkY1dnBnTUlmT21kN2Z1b0pwakZyYU1GMFhwb1htZWVKZUI2Wmk5aFNTcmkvbgp4eVUvTTQ1SkNsR3l4Z2labVVFZlYxUEYxSzVIZExCSEVqQ2tVRzJ0NnN4amI5YmwyWGpidVluV25EUlVTalZQCkNXYUpwc2RiY1pTS3lHQytwTEhSK0dsUHhiajB2WHpMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" , "UPDATE" ]
        apiGroups: ["argoproj.io"]
        apiVersions: ["v1", "v1alpha1"]
        resources: ["workflows"]