apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: gophers-test
spec:
  entrypoint: whalesay        # Defines "whalesay" as the "main" template
  templates:
  - name: whalesay            # Defining the "whalesay" template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"] 